// 젠킨스 파이프라인 플러그인을 호출하기 위한 블록
pipeline {
	// 파이프라인을 실행하고 싶은 위치 정의
	agent none
	// gitlab의 소스를 jenkins 디렉토리로 내려받을 시
	// skipDefaultCheckout(true)일 경우 내려받는 프로세스 skip
	// skipDefaultCheckout(false)일 경우 gitlab 소스 체크
	options { skipDefaultCheckout(true) }
	// stage의 모음
	stages {
		// 실제 작업이 수행되는 블록
		// 해당 stage 명으로 jenkins 화면에 표시된다
		stage('Build and Test') {
			// docker image에 명시된 image를 활용하여 steps 수행
			agent {
				docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
				}
			}
			options { skipDefaultCheckout(false) }
            // back-end build
            // -B : 비 대화식(일괄 처리) 모드에서 실행(출력 색상 비활성화)
            // 대체 pom 파일(또는 pom.xml이 있는 디렉토리)을 사용
            // -DskipTests : 테스트를 컴파일하지만, 실행을 건너 뜀
            // clean : maven build 시 생선된 모든 것들을 삭제
            // package : 컴파일을 수행하고 컴파일한 소스를 packaging 양식(war or jar)에
            // 맞춰 프로젝트 내 지정한 경로(ex. target) 디렉토리에 생성
            steps {
                sh 'mvn -B -DskipTests -f ./exec/backend/pom.xml clean package'
            }
        }
        stage('Docker build') {
            agent any
            steps {
                // front-end 및 back-end dockerfile 실행을 통해 image 생성
                // -t : 이미지 이름과 tag 설정, 만약 이미지 이름만 설정하면 latest로 설정됨
                sh 'docker build -t fridge_front:latest ./exec/frontend'
                sh 'docker build -t fridge_back:latest ./exec/backend'
            }
        }
        stage('Docker run') {
            agent any
            steps {
				// 현재 동작중인 컨테이너 중 fridge_front의 이름을 가진 컨테이너를 stop
				sh 'docker ps -f name=fridge_front -q \
					| xargs --no-run-if-empty docke_r container stop'
				// 현재 동작중인 컨테이너 중_ fridge_back의 이름을 가진 컨테이너를 stop
				sh 'docker ps -f name=fridge_back -q \
					| xargs --no-run-if-empty docker container stop'
				// fridge_front의 이름을 가진 컨테이너를 삭제
				sh 'docker container ls -a -f name=fridge_front -q \
					| xargs -r docker container rm'
				// fridge_back의 이름을 가진 컨테이너를 _삭제
				sh 'docker container ls -a -f name=fridge_back -q \
					| xargs -r docker container rm'
				// docker image build 시 기존에 존재하던 이미지는
				// dangling 상태가 되기 때문에 이미지를 일괄 삭제
				sh 'docker images -f dangling=true && \
					docker rmi $(docker images -f "dangling=true" -q)'
				// docker container 실행
				// 하나의 docker network에 연결하여 통신이 가능하도록 설정
				sh 'docker run -d --name fridge_front \
					-p 80:80 \
					-p 443:443 \
					-v /home/ubuntu/keys/:../sslkey/ \
					--network fridge_net \
					fridge_front:latest_'
				sh 'docker run -d --na_me fridge_back \
					--netw_ork fridge_net \
					fridge_back:latest'
			}
		}
	}
}